Web/Models/Products/Cereal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models
{
    public class Cereal : Product
    {
        public string Type { get; set; }
        public double Calories { get; set; }
        public double Protein { get; set; }
        public double Fat { get; set; }
        public double Sodium { get; set; }
        public double Fiber { get; set; }
        public double Carbo { get; set; }
        public double Sugars { get; set; }
        public double Potassium { get; set; }
        public int Vitamins { get; set; }
        public int Shelf { get; set; }
        public double Weight { get; set; }
        public double Cups { get; set; }
    }
   
}

Web/Controllers/CerealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web.Services;

namespace Web.Controllers
{
    public class CerealController : Controller
    {
        private readonly ICerealRepo productRepo;

        public CerealController(ICerealRepo productRepo)
        {
            this.productRepo = productRepo;
        }

        // GET: ProductController
        public ActionResult Index(string sortBy, string name, string searchParam)
        {
            var cereals = productRepo.GetCereals(sortBy, name, searchParam);
            return View(cereals);
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            var cereal = productRepo.GetCereal(id);
            return View(cereal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToCart(int id)
        {
            // TODO
            return RedirectToPage("/Cart/Index");
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/Pages/Cart/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web.Data;
using Web.Models.Cart;

namespace Web.Pages.Cart
{
    public class DetailsModel : PageModel
    {
        private readonly Web.Data.ApplicationDbContext _context;

        public DetailsModel(Web.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public CartItem CartItem { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CartItem = await _context.CartItems
                .Include(c => c.Product).FirstOrDefaultAsync(m => m.UserId == id);

            if (CartItem == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Web/Pages/Product/Beer/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web.Data;
using Web.Models.Products;

namespace Web.Pages.Product
{
    public class DetailsModel : PageModel
    {
        private readonly Web.Data.ApplicationDbContext _context;

        public DetailsModel(Web.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Beer Beer { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Beer = await _context.Beer.FirstOrDefaultAsync(m => m.Id == id);

            if (Beer == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Web/Views/Cereal/Details.cshtml
@model Cereal
﻿<section>
    <h1>@Model.Name</h1>
    @if (User.IsInRole("Admin"))
    {
        <a class="btn btn-primary"
           asp-controller="Admin"
           asp-action="Edit"
           asp-route-id="@Model.Id">Edit</a>
    }
    <div class="card-columns box-shadow">

        <p>Manufacturer: @Model.Manufacturer</p>
        <p>Type: @Model.Type</p>
        <p>Calories: @Model.Calories</p>
        <p>Protein: @Model.Protein</p>
        <p>Fat: @Model.Fat</p>
        <p>Sodium: @Model.Sodium</p>
        <p>Fiber: @Model.Fiber</p>
        <p>Carbohydrates: @Model.Carbo</p>
        <p>Sugar: @Model.Sugars</p>
        <p>Potassium: @Model.Potassium</p>
        <p>Vitamins: @Model.Vitamins</p>
        <p>Shelf: @Model.Shelf</p>
        <p>Weight: @Model.Weight</p>
        <p>Cups: @Model.Cups</p>
        <p>Rating: @Model.Rating</p>
    </div>
    <form method="post" asp-action="AddToCart" asp-controller="Cereal" asp-route-id="@Model.Id">
        <button class="btn btn-success">Add to Cart</button>
    </form>
</section>

Web/Views/Cereal/Index.cshtml
@model IEnumerable<Cereal>
    <form>
        <label><input type="radio" name="searchParam" value="Name" />Name</label>
        <label><input type="radio" name="searchParam" value="Manufacturer" />Manufacturer</label><br />
        <label><input type="text" name="name" /></label>
        <button>Search</button>
    </form>
    <form>
        <label><input type="radio" name="sortBy" value="Ascending" /> Ascending </label>
        <label><input type="radio" name="sortBy" value="Descending" /> Descending </label>
        <button>Sort</button>
    </form>
    <div class="">
        @foreach (var cereal in Model)
        {
            <section class="card text-center float-left col-5">
                <h5><a class="text-dark" href="Product/Details/@cereal.Id">@cereal.Name</a></h5>
                <div>
                    <p>Manufacturer: @cereal.Manufacturer</p>

                </div>
            </section>
        }
    </div>